//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertConfig) DeepCopyInto(out *AlertConfig) {
	*out = *in
	in.Expression.DeepCopyInto(&out.Expression)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertConfig.
func (in *AlertConfig) DeepCopy() *AlertConfig {
	if in == nil {
		return nil
	}
	out := new(AlertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoFreeze) DeepCopyInto(out *AutoFreeze) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoFreeze.
func (in *AutoFreeze) DeepCopy() *AutoFreeze {
	if in == nil {
		return nil
	}
	out := new(AutoFreeze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingConfig) DeepCopyInto(out *AutoScalingConfig) {
	*out = *in
	in.AutoSetLimits.DeepCopyInto(&out.AutoSetLimits)
	in.AutoSetReplicas.DeepCopyInto(&out.AutoSetReplicas)
	in.AutoSetRequests.DeepCopyInto(&out.AutoSetRequests)
	in.ScaleToZero.DeepCopyInto(&out.ScaleToZero)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingConfig.
func (in *AutoScalingConfig) DeepCopy() *AutoScalingConfig {
	if in == nil {
		return nil
	}
	out := new(AutoScalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoSetLimits) DeepCopyInto(out *AutoSetLimits) {
	*out = *in
	in.Prediction.DeepCopyInto(&out.Prediction)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoSetLimits.
func (in *AutoSetLimits) DeepCopy() *AutoSetLimits {
	if in == nil {
		return nil
	}
	out := new(AutoSetLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoSetReplicas) DeepCopyInto(out *AutoSetReplicas) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoSetReplicas.
func (in *AutoSetReplicas) DeepCopy() *AutoSetReplicas {
	if in == nil {
		return nil
	}
	out := new(AutoSetReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoSetRequests) DeepCopyInto(out *AutoSetRequests) {
	*out = *in
	in.Prediction.DeepCopyInto(&out.Prediction)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoSetRequests.
func (in *AutoSetRequests) DeepCopy() *AutoSetRequests {
	if in == nil {
		return nil
	}
	out := new(AutoSetRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityConfig) DeepCopyInto(out *CapacityConfig) {
	*out = *in
	out.MinResources = in.MinResources
	out.MaxResources = in.MaxResources
	out.WarmResources = in.WarmResources
	out.Oversubscription = in.Oversubscription
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityConfig.
func (in *CapacityConfig) DeepCopy() *CapacityConfig {
	if in == nil {
		return nil
	}
	out := new(CapacityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientConfig) DeepCopyInto(out *ClientConfig) {
	*out = *in
	in.PodTemplateMergePatch.DeepCopyInto(&out.PodTemplateMergePatch)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientConfig.
func (in *ClientConfig) DeepCopy() *ClientConfig {
	if in == nil {
		return nil
	}
	out := new(ClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCloudConnectionStatus) DeepCopyInto(out *ClusterCloudConnectionStatus) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCloudConnectionStatus.
func (in *ClusterCloudConnectionStatus) DeepCopy() *ClusterCloudConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterCloudConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterComputingVendorStatus) DeepCopyInto(out *ClusterComputingVendorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterComputingVendorStatus.
func (in *ClusterComputingVendorStatus) DeepCopy() *ClusterComputingVendorStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterComputingVendorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStorageStatus) DeepCopyInto(out *ClusterStorageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStorageStatus.
func (in *ClusterStorageStatus) DeepCopy() *ClusterStorageStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentConfig) DeepCopyInto(out *ComponentConfig) {
	*out = *in
	in.Worker.DeepCopyInto(&out.Worker)
	in.Hypervisor.DeepCopyInto(&out.Hypervisor)
	in.Client.DeepCopyInto(&out.Client)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentConfig.
func (in *ComponentConfig) DeepCopy() *ComponentConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputingVendorConfig) DeepCopyInto(out *ComputingVendorConfig) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	out.Params = in.Params
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputingVendorConfig.
func (in *ComputingVendorConfig) DeepCopy() *ComputingVendorConfig {
	if in == nil {
		return nil
	}
	out := new(ComputingVendorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputingVendorParams) DeepCopyInto(out *ComputingVendorParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputingVendorParams.
func (in *ComputingVendorParams) DeepCopy() *ComputingVendorParams {
	if in == nil {
		return nil
	}
	out := new(ComputingVendorParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPipeline4ResourcesConfig) DeepCopyInto(out *DataPipeline4ResourcesConfig) {
	*out = *in
	if in.SyncToCloud != nil {
		in, out := &in.SyncToCloud, &out.SyncToCloud
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPipeline4ResourcesConfig.
func (in *DataPipeline4ResourcesConfig) DeepCopy() *DataPipeline4ResourcesConfig {
	if in == nil {
		return nil
	}
	out := new(DataPipeline4ResourcesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPipeline4TimeSeriesConfig) DeepCopyInto(out *DataPipeline4TimeSeriesConfig) {
	*out = *in
	if in.AggregationPeriods != nil {
		in, out := &in.AggregationPeriods, &out.AggregationPeriods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.RemoteWrite.DeepCopyInto(&out.RemoteWrite)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPipeline4TimeSeriesConfig.
func (in *DataPipeline4TimeSeriesConfig) DeepCopy() *DataPipeline4TimeSeriesConfig {
	if in == nil {
		return nil
	}
	out := new(DataPipeline4TimeSeriesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPipelineResultRemoteWriteConfig) DeepCopyInto(out *DataPipelineResultRemoteWriteConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPipelineResultRemoteWriteConfig.
func (in *DataPipelineResultRemoteWriteConfig) DeepCopy() *DataPipelineResultRemoteWriteConfig {
	if in == nil {
		return nil
	}
	out := new(DataPipelineResultRemoteWriteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPipelinesConfig) DeepCopyInto(out *DataPipelinesConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.Timeseries.DeepCopyInto(&out.Timeseries)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPipelinesConfig.
func (in *DataPipelinesConfig) DeepCopy() *DataPipelinesConfig {
	if in == nil {
		return nil
	}
	out := new(DataPipelinesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnrollConfig) DeepCopyInto(out *EnrollConfig) {
	*out = *in
	out.EnrollKey = in.EnrollKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnrollConfig.
func (in *EnrollConfig) DeepCopy() *EnrollConfig {
	if in == nil {
		return nil
	}
	out := new(EnrollConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnrollmentKeyConfig) DeepCopyInto(out *EnrollmentKeyConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnrollmentKeyConfig.
func (in *EnrollmentKeyConfig) DeepCopy() *EnrollmentKeyConfig {
	if in == nil {
		return nil
	}
	out := new(EnrollmentKeyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPU) DeepCopyInto(out *GPU) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPU.
func (in *GPU) DeepCopy() *GPU {
	if in == nil {
		return nil
	}
	out := new(GPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPU) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFilter) DeepCopyInto(out *GPUFilter) {
	*out = *in
	in.Params.DeepCopyInto(&out.Params)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFilter.
func (in *GPUFilter) DeepCopy() *GPUFilter {
	if in == nil {
		return nil
	}
	out := new(GPUFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUList) DeepCopyInto(out *GPUList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPU, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUList.
func (in *GPUList) DeepCopy() *GPUList {
	if in == nil {
		return nil
	}
	out := new(GPUList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNode) DeepCopyInto(out *GPUNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNode.
func (in *GPUNode) DeepCopy() *GPUNode {
	if in == nil {
		return nil
	}
	out := new(GPUNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeClass) DeepCopyInto(out *GPUNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeClass.
func (in *GPUNodeClass) DeepCopy() *GPUNodeClass {
	if in == nil {
		return nil
	}
	out := new(GPUNodeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeClassList) DeepCopyInto(out *GPUNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeClassList.
func (in *GPUNodeClassList) DeepCopy() *GPUNodeClassList {
	if in == nil {
		return nil
	}
	out := new(GPUNodeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeClassSpec) DeepCopyInto(out *GPUNodeClassSpec) {
	*out = *in
	if in.OSImageSelectorTerms != nil {
		in, out := &in.OSImageSelectorTerms, &out.OSImageSelectorTerms
		*out = make([]NodeClassOSImageSelectorTerms, len(*in))
		copy(*out, *in)
	}
	if in.BlockDeviceMappings != nil {
		in, out := &in.BlockDeviceMappings, &out.BlockDeviceMappings
		*out = make([]NodeClassBlockDeviceMappings, len(*in))
		copy(*out, *in)
	}
	out.MetadataOptions = in.MetadataOptions
	if in.SecurityGroupSelectorTerms != nil {
		in, out := &in.SecurityGroupSelectorTerms, &out.SecurityGroupSelectorTerms
		*out = make([]NodeClassItemIDSelectorTerms, len(*in))
		copy(*out, *in)
	}
	if in.SubnetSelectorTerms != nil {
		in, out := &in.SubnetSelectorTerms, &out.SubnetSelectorTerms
		*out = make([]NodeClassItemIDSelectorTerms, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeClassSpec.
func (in *GPUNodeClassSpec) DeepCopy() *GPUNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(GPUNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeClassStatus) DeepCopyInto(out *GPUNodeClassStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeClassStatus.
func (in *GPUNodeClassStatus) DeepCopy() *GPUNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeInfo) DeepCopyInto(out *GPUNodeInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeInfo.
func (in *GPUNodeInfo) DeepCopy() *GPUNodeInfo {
	if in == nil {
		return nil
	}
	out := new(GPUNodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeList) DeepCopyInto(out *GPUNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeList.
func (in *GPUNodeList) DeepCopy() *GPUNodeList {
	if in == nil {
		return nil
	}
	out := new(GPUNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeSpec) DeepCopyInto(out *GPUNodeSpec) {
	*out = *in
	if in.GPUCardIndices != nil {
		in, out := &in.GPUCardIndices, &out.GPUCardIndices
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeSpec.
func (in *GPUNodeSpec) DeepCopy() *GPUNodeSpec {
	if in == nil {
		return nil
	}
	out := new(GPUNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeStatus) DeepCopyInto(out *GPUNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.HypervisorStatus.DeepCopyInto(&out.HypervisorStatus)
	out.NodeInfo = in.NodeInfo
	if in.LoadedModels != nil {
		in, out := &in.LoadedModels, &out.LoadedModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedGPUResourceIDs != nil {
		in, out := &in.ManagedGPUResourceIDs, &out.ManagedGPUResourceIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeStatus.
func (in *GPUNodeStatus) DeepCopy() *GPUNodeStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPool) DeepCopyInto(out *GPUPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPool.
func (in *GPUPool) DeepCopy() *GPUPool {
	if in == nil {
		return nil
	}
	out := new(GPUPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolDefinition) DeepCopyInto(out *GPUPoolDefinition) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolDefinition.
func (in *GPUPoolDefinition) DeepCopy() *GPUPoolDefinition {
	if in == nil {
		return nil
	}
	out := new(GPUPoolDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolList) DeepCopyInto(out *GPUPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolList.
func (in *GPUPoolList) DeepCopy() *GPUPoolList {
	if in == nil {
		return nil
	}
	out := new(GPUPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolSpec) DeepCopyInto(out *GPUPoolSpec) {
	*out = *in
	out.CapacityConfig = in.CapacityConfig
	in.NodeManagerConfig.DeepCopyInto(&out.NodeManagerConfig)
	in.ObservabilityConfig.DeepCopyInto(&out.ObservabilityConfig)
	in.QosConfig.DeepCopyInto(&out.QosConfig)
	in.ComponentConfig.DeepCopyInto(&out.ComponentConfig)
	in.SchedulingConfig.DeepCopyInto(&out.SchedulingConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolSpec.
func (in *GPUPoolSpec) DeepCopy() *GPUPoolSpec {
	if in == nil {
		return nil
	}
	out := new(GPUPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolStatus) DeepCopyInto(out *GPUPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ProvisioningStatus = in.ProvisioningStatus
	out.ComponentStatus = in.ComponentStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolStatus.
func (in *GPUPoolStatus) DeepCopy() *GPUPoolStatus {
	if in == nil {
		return nil
	}
	out := new(GPUPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUResourceUnit) DeepCopyInto(out *GPUResourceUnit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUResourceUnit.
func (in *GPUResourceUnit) DeepCopy() *GPUResourceUnit {
	if in == nil {
		return nil
	}
	out := new(GPUResourceUnit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUStatus) DeepCopyInto(out *GPUStatus) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Capacity.DeepCopyInto(&out.Capacity)
	in.Available.DeepCopyInto(&out.Available)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUStatus.
func (in *GPUStatus) DeepCopy() *GPUStatus {
	if in == nil {
		return nil
	}
	out := new(GPUStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfig) DeepCopyInto(out *HypervisorConfig) {
	*out = *in
	in.HypervisorDaemonSetTemplate.DeepCopyInto(&out.HypervisorDaemonSetTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfig.
func (in *HypervisorConfig) DeepCopy() *HypervisorConfig {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorScheduling) DeepCopyInto(out *HypervisorScheduling) {
	*out = *in
	in.MultiProcessQueuing.DeepCopyInto(&out.MultiProcessQueuing)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorScheduling.
func (in *HypervisorScheduling) DeepCopy() *HypervisorScheduling {
	if in == nil {
		return nil
	}
	out := new(HypervisorScheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	if in.Includes != nil {
		in, out := &in.Includes, &out.Includes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorConfig) DeepCopyInto(out *MonitorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorConfig.
func (in *MonitorConfig) DeepCopy() *MonitorConfig {
	if in == nil {
		return nil
	}
	out := new(MonitorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiProcessQueuing) DeepCopyInto(out *MultiProcessQueuing) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.QueueLevelTimeSlices != nil {
		in, out := &in.QueueLevelTimeSlices, &out.QueueLevelTimeSlices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiProcessQueuing.
func (in *MultiProcessQueuing) DeepCopy() *MultiProcessQueuing {
	if in == nil {
		return nil
	}
	out := new(MultiProcessQueuing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameNamespace) DeepCopyInto(out *NameNamespace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameNamespace.
func (in *NameNamespace) DeepCopy() *NameNamespace {
	if in == nil {
		return nil
	}
	out := new(NameNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClassBlockDeviceMappings) DeepCopyInto(out *NodeClassBlockDeviceMappings) {
	*out = *in
	out.Ebs = in.Ebs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClassBlockDeviceMappings.
func (in *NodeClassBlockDeviceMappings) DeepCopy() *NodeClassBlockDeviceMappings {
	if in == nil {
		return nil
	}
	out := new(NodeClassBlockDeviceMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClassEbsSettings) DeepCopyInto(out *NodeClassEbsSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClassEbsSettings.
func (in *NodeClassEbsSettings) DeepCopy() *NodeClassEbsSettings {
	if in == nil {
		return nil
	}
	out := new(NodeClassEbsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClassItemIDSelectorTerms) DeepCopyInto(out *NodeClassItemIDSelectorTerms) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClassItemIDSelectorTerms.
func (in *NodeClassItemIDSelectorTerms) DeepCopy() *NodeClassItemIDSelectorTerms {
	if in == nil {
		return nil
	}
	out := new(NodeClassItemIDSelectorTerms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClassMetadataOptions) DeepCopyInto(out *NodeClassMetadataOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClassMetadataOptions.
func (in *NodeClassMetadataOptions) DeepCopy() *NodeClassMetadataOptions {
	if in == nil {
		return nil
	}
	out := new(NodeClassMetadataOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClassOSImageSelectorTerms) DeepCopyInto(out *NodeClassOSImageSelectorTerms) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClassOSImageSelectorTerms.
func (in *NodeClassOSImageSelectorTerms) DeepCopy() *NodeClassOSImageSelectorTerms {
	if in == nil {
		return nil
	}
	out := new(NodeClassOSImageSelectorTerms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCompaction) DeepCopyInto(out *NodeCompaction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCompaction.
func (in *NodeCompaction) DeepCopy() *NodeCompaction {
	if in == nil {
		return nil
	}
	out := new(NodeCompaction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHypervisorStatus) DeepCopyInto(out *NodeHypervisorStatus) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHypervisorStatus.
func (in *NodeHypervisorStatus) DeepCopy() *NodeHypervisorStatus {
	if in == nil {
		return nil
	}
	out := new(NodeHypervisorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeManagerConfig) DeepCopyInto(out *NodeManagerConfig) {
	*out = *in
	in.NodeProvisioner.DeepCopyInto(&out.NodeProvisioner)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(NodeSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.NodeCompaction = in.NodeCompaction
	in.NodePoolRollingUpdatePolicy.DeepCopyInto(&out.NodePoolRollingUpdatePolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeManagerConfig.
func (in *NodeManagerConfig) DeepCopy() *NodeManagerConfig {
	if in == nil {
		return nil
	}
	out := new(NodeManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeProvisioner) DeepCopyInto(out *NodeProvisioner) {
	*out = *in
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]Requirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]Taint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeProvisioner.
func (in *NodeProvisioner) DeepCopy() *NodeProvisioner {
	if in == nil {
		return nil
	}
	out := new(NodeProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRollingUpdatePolicy) DeepCopyInto(out *NodeRollingUpdatePolicy) {
	*out = *in
	if in.AutoUpdate != nil {
		in, out := &in.AutoUpdate, &out.AutoUpdate
		*out = new(bool)
		**out = **in
	}
	in.MaintenanceWindow.DeepCopyInto(&out.MaintenanceWindow)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRollingUpdatePolicy.
func (in *NodeRollingUpdatePolicy) DeepCopy() *NodeRollingUpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(NodeRollingUpdatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NodeSelector) DeepCopyInto(out *NodeSelector) {
	{
		in := &in
		*out = make(NodeSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelector.
func (in NodeSelector) DeepCopy() NodeSelector {
	if in == nil {
		return nil
	}
	out := new(NodeSelector)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSelectorItem) DeepCopyInto(out *NodeSelectorItem) {
	*out = *in
	if in.MatchAny != nil {
		in, out := &in.MatchAny, &out.MatchAny
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchAll != nil {
		in, out := &in.MatchAll, &out.MatchAll
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelectorItem.
func (in *NodeSelectorItem) DeepCopy() *NodeSelectorItem {
	if in == nil {
		return nil
	}
	out := new(NodeSelectorItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityConfig) DeepCopyInto(out *ObservabilityConfig) {
	*out = *in
	out.Monitor = in.Monitor
	in.Alert.DeepCopyInto(&out.Alert)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityConfig.
func (in *ObservabilityConfig) DeepCopy() *ObservabilityConfig {
	if in == nil {
		return nil
	}
	out := new(ObservabilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Oversubscription) DeepCopyInto(out *Oversubscription) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Oversubscription.
func (in *Oversubscription) DeepCopy() *Oversubscription {
	if in == nil {
		return nil
	}
	out := new(Oversubscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementConfig) DeepCopyInto(out *PlacementConfig) {
	*out = *in
	if in.AllowUsingLocalGPU != nil {
		in, out := &in.AllowUsingLocalGPU, &out.AllowUsingLocalGPU
		*out = new(bool)
		**out = **in
	}
	if in.GPUFilters != nil {
		in, out := &in.GPUFilters, &out.GPUFilters
		*out = make([]GPUFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementConfig.
func (in *PlacementConfig) DeepCopy() *PlacementConfig {
	if in == nil {
		return nil
	}
	out := new(PlacementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolComponentStatus) DeepCopyInto(out *PoolComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolComponentStatus.
func (in *PoolComponentStatus) DeepCopy() *PoolComponentStatus {
	if in == nil {
		return nil
	}
	out := new(PoolComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolProvisioningStatus) DeepCopyInto(out *PoolProvisioningStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolProvisioningStatus.
func (in *PoolProvisioningStatus) DeepCopy() *PoolProvisioningStatus {
	if in == nil {
		return nil
	}
	out := new(PoolProvisioningStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosConfig) DeepCopyInto(out *QosConfig) {
	*out = *in
	if in.Definitions != nil {
		in, out := &in.Definitions, &out.Definitions
		*out = make([]QosDefinition, len(*in))
		copy(*out, *in)
	}
	if in.Pricing != nil {
		in, out := &in.Pricing, &out.Pricing
		*out = make([]QosPricing, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosConfig.
func (in *QosConfig) DeepCopy() *QosConfig {
	if in == nil {
		return nil
	}
	out := new(QosConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosDefinition) DeepCopyInto(out *QosDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosDefinition.
func (in *QosDefinition) DeepCopy() *QosDefinition {
	if in == nil {
		return nil
	}
	out := new(QosDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosPricing) DeepCopyInto(out *QosPricing) {
	*out = *in
	out.Requests = in.Requests
	out.LimitsOverRequests = in.LimitsOverRequests
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosPricing.
func (in *QosPricing) DeepCopy() *QosPricing {
	if in == nil {
		return nil
	}
	out := new(QosPricing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReBalanceThreshold) DeepCopyInto(out *ReBalanceThreshold) {
	*out = *in
	in.MatchAny.DeepCopyInto(&out.MatchAny)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReBalanceThreshold.
func (in *ReBalanceThreshold) DeepCopy() *ReBalanceThreshold {
	if in == nil {
		return nil
	}
	out := new(ReBalanceThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReBalancerConfig) DeepCopyInto(out *ReBalancerConfig) {
	*out = *in
	in.Threshold.DeepCopyInto(&out.Threshold)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReBalancerConfig.
func (in *ReBalancerConfig) DeepCopy() *ReBalancerConfig {
	if in == nil {
		return nil
	}
	out := new(ReBalancerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteWriteConfig) DeepCopyInto(out *RemoteWriteConfig) {
	*out = *in
	out.Connection = in.Connection
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteWriteConfig.
func (in *RemoteWriteConfig) DeepCopy() *RemoteWriteConfig {
	if in == nil {
		return nil
	}
	out := new(RemoteWriteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Requirement) DeepCopyInto(out *Requirement) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Requirement.
func (in *Requirement) DeepCopy() *Requirement {
	if in == nil {
		return nil
	}
	out := new(Requirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	out.Tflops = in.Tflops.DeepCopy()
	out.Vram = in.Vram.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	in.Requests.DeepCopyInto(&out.Requests)
	in.Limits.DeepCopyInto(&out.Limits)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleToZero) DeepCopyInto(out *ScaleToZero) {
	*out = *in
	if in.AutoFreeze != nil {
		in, out := &in.AutoFreeze, &out.AutoFreeze
		*out = make([]AutoFreeze, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.IntelligenceWarmup.DeepCopyInto(&out.IntelligenceWarmup)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleToZero.
func (in *ScaleToZero) DeepCopy() *ScaleToZero {
	if in == nil {
		return nil
	}
	out := new(ScaleToZero)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingConfigTemplate) DeepCopyInto(out *SchedulingConfigTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingConfigTemplate.
func (in *SchedulingConfigTemplate) DeepCopy() *SchedulingConfigTemplate {
	if in == nil {
		return nil
	}
	out := new(SchedulingConfigTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulingConfigTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingConfigTemplateList) DeepCopyInto(out *SchedulingConfigTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SchedulingConfigTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingConfigTemplateList.
func (in *SchedulingConfigTemplateList) DeepCopy() *SchedulingConfigTemplateList {
	if in == nil {
		return nil
	}
	out := new(SchedulingConfigTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulingConfigTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingConfigTemplateSpec) DeepCopyInto(out *SchedulingConfigTemplateSpec) {
	*out = *in
	in.Placement.DeepCopyInto(&out.Placement)
	in.AutoScaling.DeepCopyInto(&out.AutoScaling)
	in.ReBalancer.DeepCopyInto(&out.ReBalancer)
	in.Hypervisor.DeepCopyInto(&out.Hypervisor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingConfigTemplateSpec.
func (in *SchedulingConfigTemplateSpec) DeepCopy() *SchedulingConfigTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulingConfigTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingConfigTemplateStatus) DeepCopyInto(out *SchedulingConfigTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingConfigTemplateStatus.
func (in *SchedulingConfigTemplateStatus) DeepCopy() *SchedulingConfigTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(SchedulingConfigTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmartSchedulerModelInput) DeepCopyInto(out *SmartSchedulerModelInput) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmartSchedulerModelInput.
func (in *SmartSchedulerModelInput) DeepCopy() *SmartSchedulerModelInput {
	if in == nil {
		return nil
	}
	out := new(SmartSchedulerModelInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageVendorConfig) DeepCopyInto(out *StorageVendorConfig) {
	*out = *in
	if in.InstallCloudNativePGOperator != nil {
		in, out := &in.InstallCloudNativePGOperator, &out.InstallCloudNativePGOperator
		*out = new(bool)
		**out = **in
	}
	if in.PGExtensions != nil {
		in, out := &in.PGExtensions, &out.PGExtensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.PGClusterTemplate.DeepCopyInto(&out.PGClusterTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageVendorConfig.
func (in *StorageVendorConfig) DeepCopy() *StorageVendorConfig {
	if in == nil {
		return nil
	}
	out := new(StorageVendorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Taint) DeepCopyInto(out *Taint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Taint.
func (in *Taint) DeepCopy() *Taint {
	if in == nil {
		return nil
	}
	out := new(Taint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorFusionCluster) DeepCopyInto(out *TensorFusionCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorFusionCluster.
func (in *TensorFusionCluster) DeepCopy() *TensorFusionCluster {
	if in == nil {
		return nil
	}
	out := new(TensorFusionCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TensorFusionCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorFusionClusterList) DeepCopyInto(out *TensorFusionClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TensorFusionCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorFusionClusterList.
func (in *TensorFusionClusterList) DeepCopy() *TensorFusionClusterList {
	if in == nil {
		return nil
	}
	out := new(TensorFusionClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TensorFusionClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorFusionClusterSpec) DeepCopyInto(out *TensorFusionClusterSpec) {
	*out = *in
	out.Enroll = in.Enroll
	if in.GPUPools != nil {
		in, out := &in.GPUPools, &out.GPUPools
		*out = make([]GPUPoolDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ComputingVendor.DeepCopyInto(&out.ComputingVendor)
	in.StorageVendor.DeepCopyInto(&out.StorageVendor)
	in.DataPipelines.DeepCopyInto(&out.DataPipelines)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorFusionClusterSpec.
func (in *TensorFusionClusterSpec) DeepCopy() *TensorFusionClusterSpec {
	if in == nil {
		return nil
	}
	out := new(TensorFusionClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorFusionClusterStatus) DeepCopyInto(out *TensorFusionClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReadyGPUPools != nil {
		in, out := &in.ReadyGPUPools, &out.ReadyGPUPools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotReadyGPUPools != nil {
		in, out := &in.NotReadyGPUPools, &out.NotReadyGPUPools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LicenseRenewalTime.DeepCopyInto(&out.LicenseRenewalTime)
	in.CloudConnectionStatus.DeepCopyInto(&out.CloudConnectionStatus)
	out.StorageStatus = in.StorageStatus
	out.ComputingVendorStatus = in.ComputingVendorStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorFusionClusterStatus.
func (in *TensorFusionClusterStatus) DeepCopy() *TensorFusionClusterStatus {
	if in == nil {
		return nil
	}
	out := new(TensorFusionClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorFusionConnection) DeepCopyInto(out *TensorFusionConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorFusionConnection.
func (in *TensorFusionConnection) DeepCopy() *TensorFusionConnection {
	if in == nil {
		return nil
	}
	out := new(TensorFusionConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TensorFusionConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorFusionConnectionList) DeepCopyInto(out *TensorFusionConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TensorFusionConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorFusionConnectionList.
func (in *TensorFusionConnectionList) DeepCopy() *TensorFusionConnectionList {
	if in == nil {
		return nil
	}
	out := new(TensorFusionConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TensorFusionConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorFusionConnectionSpec) DeepCopyInto(out *TensorFusionConnectionSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorFusionConnectionSpec.
func (in *TensorFusionConnectionSpec) DeepCopy() *TensorFusionConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(TensorFusionConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorFusionConnectionStatus) DeepCopyInto(out *TensorFusionConnectionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorFusionConnectionStatus.
func (in *TensorFusionConnectionStatus) DeepCopy() *TensorFusionConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(TensorFusionConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerConfig) DeepCopyInto(out *WorkerConfig) {
	*out = *in
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(bool)
		**out = **in
	}
	in.WorkerPodTemplate.DeepCopyInto(&out.WorkerPodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerConfig.
func (in *WorkerConfig) DeepCopy() *WorkerConfig {
	if in == nil {
		return nil
	}
	out := new(WorkerConfig)
	in.DeepCopyInto(out)
	return out
}
