resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# The following RBAC configurations are used to protect
# the metrics endpoint with authn/authz. These configurations
# ensure that only authorized users and service accounts
# can access the metrics endpoint. Comment the following
# permissions if you want to disable this protection.
# More info: https://book.kubebuilder.io/reference/metrics.html
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
# For each CRD, "Editor" and "Viewer" roles are scaffolded by
# default, aiding admins in cluster management. Those roles are
# not used by the Project itself. You can comment the following lines
# if you do not want those helpers be installed with your Project.
- tensorfusionworkload_editor_role.yaml
- tensorfusionworkload_viewer_role.yaml
- workloadprofile_editor_role.yaml
- workloadprofile_viewer_role.yaml
- schedulingconfigtemplate_editor_role.yaml
- schedulingconfigtemplate_viewer_role.yaml
- gpunodeclass_editor_role.yaml
- gpunodeclass_viewer_role.yaml
- gpunode_editor_role.yaml
- gpunode_viewer_role.yaml
- gpupool_editor_role.yaml
- gpupool_viewer_role.yaml
- tensorfusioncluster_editor_role.yaml
- tensorfusioncluster_viewer_role.yaml
- gpu_editor_role.yaml
- gpu_viewer_role.yaml
- tensorfusionconnection_editor_role.yaml
- tensorfusionconnection_viewer_role.yaml
- gpunodeclaim_admin_role.yaml
- gpunodeclaim_editor_role.yaml
- gpunodeclaim_viewer_role.yaml