name: Tests

on:
  push:
    branches:
      - main
      - release/**
    paths-ignore:
      - "*.md"
      - "charts/**"
      - "config/**"
  pull_request:
    branches:
      - main
      - release/**
    paths-ignore:
      - "*.md"
      - "charts/**"
      - "config/**"

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.24'

      - name: Running Tests
        run: |
          go mod tidy
          make test
