name: Tests

on:
  push:
    branches:
      - main
      - release/**
    paths-ignore:
      - "*.md"
      - "charts/**"
      - "config/**"
  pull_request:
    branches:
      - main
      - release/**
    paths-ignore:
      - "*.md"
      - "charts/**"
      - "config/**"

permissions:
  contents: read

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # from https://github.com/kubernetes-sigs/controller-tools/blob/main/envtest-releases.yaml
        envtest_k8s_version: [1.23.5, 1.33.0]
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.24'

      - name: Running Tests
        run: |
          go mod tidy
          make test
        env:
          ENVTEST_K8S_VERSION: ${{ matrix.envtest_k8s_version }}
